name: Deploy to Surge.sh

# Se ejecuta en push a main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Paso 1: Descargar código del repositorio
    - name: Checkout
      uses: actions/checkout@v4
      
    # Paso 2: Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    # Paso 3: Instalar Surge.sh globalmente
    - name: Install Surge
      run: npm install -g surge
      
    # Paso 4: Desplegar a Surge.sh
    - name: Deploy to Surge.sh
      run: |
        echo "Desplegando sitio web a Surge.sh..."
        echo "machine surge.surge.sh" > ~/.netrc
        echo "  login wilmargomezdelacrus655@gmail.com" >> ~/.netrc
        echo "  password ${{ secrets.WILMAR_10_ELECTIVA_2_2025 }}" >> ~/.netrc
        chmod 600 ~/.netrc
        surge . WILMAR_10_ELECTIVA_2_2025.surge.sh
        
    # Paso 5: Notificar éxito del despliegue
    - name: Deployment success notification
      if: success()
      run: |
        echo "Despliegue exitoso a https://WILMAR_10_ELECTIVA_2_2025.surge.sh"